export const base: string;
export const header:string;
export const title: string;
export const account: string;
export const fabCamera: string;
export const gridList: string;
export const gridCtnr: string;
export const footer: string;
export const footerNav: string;
export const refri: string;