# Generated by Django 2.1.7 on 2019-02-20 04:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=30, null=True)),
                ('count', models.IntegerField(max_length=30, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
