# Generated by Django 2.1.7 on 2019-02-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
    ]
